export const templateRisks = [
  {
    id: "t1",
    riskId: "RR-IT-2025-01",
    dateOfIdentification: "2025-01-15",
    location: "Head Office",
    riskType: "Operational",
    riskFor: "Information Security",
    riskStatement: "Unauthorized access to sensitive data",
    department: "IT",
    owner: "John Doe",
    asset: "Database Server",
    c: 2,
    i: 3,
    a: 2,
    assetValue: 7,
    impact: 3,
    likelihood: 3,
    riskScore: 9,
    riskLevel: "High",
    action: "Mitigate",
    existingControls: "Access controls, encryption",
    isoControlRef: "ISO 27001 A.9",
    tpLikelihood: 2,
    tpImpact: 2,
    tpRiskScore: 4,
    tpRiskLevel: "Medium",
    tpAction: "Mitigate",
    compensatoryControls: "Monitoring tools",
    plan: "Enhance IAM policies",
    dateOfClosure: "",
    status: "Open",
    verifiedBy: "",
    frequencyOfMonitoring: "Monthly",
    remarks: "Critical system"
  },
  {
    id: "t2",
    riskId: "RR-FIN-2025-02",
    dateOfIdentification: "2025-02-10",
    location: "Finance Dept",
    riskType: "Strategic",
    riskFor: "Data Privacy",
    riskStatement: "Non-compliance with data retention policy",
    department: "Finance",
    owner: "Jane Smith",
    asset: "Financial Records",
    c: 3,
    i: 2,
    a: 1,
    assetValue: 6,
    impact: 2,
    likelihood: 2,
    riskScore: 4,
    riskLevel: "Medium",
    action: "Mitigate",
    existingControls: "Archival system",
    isoControlRef: "ISO 27001 A.18",
    tpLikelihood: 1,
    tpImpact: 2,
    tpRiskScore: 2,
    tpRiskLevel: "Low",
    tpAction: "Accept",
    compensatoryControls: "Audit checks",
    plan: "Implement retention automation",
    dateOfClosure: "",
    status: "In Progress",
    verifiedBy: "",
    frequencyOfMonitoring: "Quarterly",
    remarks: ""
  }
];
